# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-09 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetryslam', '0002_auto_20170621_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverseparticipant',
            name='preferredCity',
            field=models.CharField(choices=[('Goa', 'Goa'), ('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai')], max_length=20),
        ),
    ]
