# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spinoff', '0002_auto_20170621_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spinoffparticipant',
            name='preferredCity',
            field=models.CharField(choices=[('Bangalore', 'Bangalore'), ('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Delhi', 'Delhi')], max_length=20),
        ),
    ]
